/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * crazychat.java
 *
 * Created on 19 févr. 2011, 08:58:46
 */

package chat.client.gui;

/**
 *
 * @author NargiT
 */
public class crazychat extends javax.swing.JPanel {

    /** Creates new form crazychat */
    public crazychat() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        fileItem = new javax.swing.JMenuItem();
        quitItem = new javax.swing.JMenuItem();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        menuBar.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                menuBarComponentShown(evt);
            }
        });

        menu.setText("File");

        fileItem.setText("Connect...");
        menu.add(fileItem);

        quitItem.setText("Quit");
        menu.add(quitItem);

        menuBar.add(menu);

        setLayout(new java.awt.BorderLayout(5, 5));

        jSplitPane1.setDividerLocation(300);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel1.setLayout(new java.awt.GridLayout(1, 2, 5, 5));

        jEditorPane1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jScrollPane1.setViewportView(jEditorPane1);

        jPanel1.add(jScrollPane1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Send");
        jButton1.setActionCommand("send");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 40));

        jPanel1.add(jPanel2);

        jSplitPane1.setBottomComponent(jPanel1);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void menuBarComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_menuBarComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_menuBarComponentShown

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem fileItem;
    private javax.swing.JButton jButton1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JMenu menu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem quitItem;
    // End of variables declaration//GEN-END:variables

}
