/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * crazyform.java
 *
 * Created on 19 févr. 2011, 17:39:51
 */
package chat.client.gui;

import java.awt.Color;

/**
 *
 * @author NargiT
 */
public class crazyform extends javax.swing.JFrame {

    /** Creates new form crazyform */
    public crazyform() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        inputPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jLabel1 = new javax.swing.JLabel();
        outPanel = new javax.swing.JPanel();
        outputSplitPanel = new javax.swing.JSplitPane();
        clientsScrollPanel = new javax.swing.JScrollPane();
        clientsPanel = new javax.swing.JPanel();
        aClient1 = new chat.client.gui.aClient();
        ouputPanel = new javax.swing.JPanel();
        MenuBar = new javax.swing.JMenuBar();
        CrazyChat = new javax.swing.JMenu();
        ConnectionItem = new javax.swing.JMenuItem();
        QuitItem = new javax.swing.JMenuItem();
        Options = new javax.swing.JMenu();
        HistoryMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerSize(7);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setResizeWeight(1.0);

        inputPanel.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jEditorPane1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jEditorPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jEditorPane1.setDoubleBuffered(true);
        jEditorPane1.setMargin(new java.awt.Insets(3, 3, 3, 15));
        jEditorPane1.setMinimumSize(new java.awt.Dimension(0, 0));
        jScrollPane2.setViewportView(jEditorPane1);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chat/client/gui/icone/send.png"))); // NOI18N
        jLabel1.setLabelFor(jScrollPane2);

        javax.swing.GroupLayout inputPanelLayout = new javax.swing.GroupLayout(inputPanel);
        inputPanel.setLayout(inputPanelLayout);
        inputPanelLayout.setHorizontalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inputPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        inputPanelLayout.setVerticalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(11, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(inputPanel);

        outputSplitPanel.setDividerSize(7);
        outputSplitPanel.setResizeWeight(1.0);

        clientsScrollPanel.setBorder(null);
        clientsScrollPanel.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        clientsPanel.setBackground(new java.awt.Color(255, 255, 255));
        clientsPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        clientsPanel.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout clientsPanelLayout = new javax.swing.GroupLayout(clientsPanel);
        clientsPanel.setLayout(clientsPanelLayout);
        clientsPanelLayout.setHorizontalGroup(
            clientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientsPanelLayout.createSequentialGroup()
                .addComponent(aClient1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        clientsPanelLayout.setVerticalGroup(
            clientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientsPanelLayout.createSequentialGroup()
                .addComponent(aClient1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(274, Short.MAX_VALUE))
        );

        clientsScrollPanel.setViewportView(clientsPanel);

        outputSplitPanel.setRightComponent(clientsScrollPanel);

        ouputPanel.setBackground(new java.awt.Color(255, 102, 102));
        ouputPanel.setPreferredSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout ouputPanelLayout = new javax.swing.GroupLayout(ouputPanel);
        ouputPanel.setLayout(ouputPanelLayout);
        ouputPanelLayout.setHorizontalGroup(
            ouputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 433, Short.MAX_VALUE)
        );
        ouputPanelLayout.setVerticalGroup(
            ouputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 294, Short.MAX_VALUE)
        );

        outputSplitPanel.setLeftComponent(ouputPanel);

        javax.swing.GroupLayout outPanelLayout = new javax.swing.GroupLayout(outPanel);
        outPanel.setLayout(outPanelLayout);
        outPanelLayout.setHorizontalGroup(
            outPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 557, Short.MAX_VALUE)
            .addGroup(outPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(outputSplitPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE))
        );
        outPanelLayout.setVerticalGroup(
            outPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 296, Short.MAX_VALUE)
            .addGroup(outPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(outputSplitPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE))
        );

        jSplitPane1.setTopComponent(outPanel);

        CrazyChat.setText("CrazyChat");

        ConnectionItem.setText("Connection...");
        CrazyChat.add(ConnectionItem);

        QuitItem.setText("Quit");
        CrazyChat.add(QuitItem);

        MenuBar.add(CrazyChat);

        Options.setText("Options");

        HistoryMenu.setText("History...");
        Options.add(HistoryMenu);

        MenuBar.add(Options);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new crazyform().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ConnectionItem;
    private javax.swing.JMenu CrazyChat;
    private javax.swing.JMenuItem HistoryMenu;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenu Options;
    private javax.swing.JMenuItem QuitItem;
    private chat.client.gui.aClient aClient1;
    private javax.swing.JPanel clientsPanel;
    private javax.swing.JScrollPane clientsScrollPanel;
    private javax.swing.JPanel inputPanel;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel ouputPanel;
    private javax.swing.JPanel outPanel;
    private javax.swing.JSplitPane outputSplitPanel;
    // End of variables declaration//GEN-END:variables
}
